language: node_js

node_js:
  - lts/*

script:
  - npm run lint
  - npm run build

after_success:
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then bash ./scripts/deploy.sh; fi  
cache:
  npm: true
  directories:
  - node_modules
   
